# Too bad need a tool for stow!!

[tools]
usage = "latest"

[vars]
verbose_arg = '--verbose'

[tasks.stow-home]
hide = true
description = "Stows a package into your home directory"
run = 'stow --dir config --target /home/cortman --dotfiles {{vars.verbose_arg}} {{arg(name="package")}}'

[tasks.stow-xdg]
hide = true
description = "Stows a package into ~/.config"
run = 'stow --dir config --target /home/cortman/.config --dotfiles {{vars.verbose_arg}} {{arg(name="package")}}'

[tasks.stow]
description = """
Uses gnu stow to install the config for the given package
There are two inocations. Any package that starts with an underscore will go to the .config folder
this way I don't have to have hidden .config folders in the tree
"""
run = [
  # Stow will fail if the ~/.config/*** dirs do not exist
  './create_config_dirs.sh',
  # symlink our dotfiles that go directly into the home folder
  'eza -D -1 -I "_*" config | xargs stow --dir config --target /home/cortman --dotfiles {{vars.verbose_arg}}',
  # symlink the dotfiles that go into ~/.config
  'eza -D -1 -I "[a-z]*" config | xargs stow --dir config --target /home/cortman/.config --dotfiles {{vars.verbose_arg}}',
]


[tasks.list-configs]
hide = true
quiet = true
description = "List the stow packages"
run = 'eza -D -1 config'
