# Too bad need a tool for stow!!

[tools]
jj = "latest"
usage = "latest"

[vars]
verbose_arg = '--verbose'
home_dir = "{{ get_env(name='HOME', default='/tmp') }}"

[tasks.stow-home]
hide = true
description = "Stows a package into your home directory"
run = 'stow --dir config --target {{vars.home_dir}} --dotfiles {{vars.verbose_arg}} {{arg(name="package")}}'

[tasks.stow-xdg]
hide = true
description = "Stows a package into ~/.config"
run = 'stow --dir config --target {{vars.home_dir}}/.config --dotfiles {{vars.verbose_arg}} {{arg(name="package")}}'

[tasks.stow]
description = """
Uses gnu stow to install the config for the given package
There are two inocations. Any package that starts with an underscore will go to the .config folder
this way I don't have to have hidden .config folders in the tree
"""
depends = ["create_config_dirs"]
run = [
  # './create_config_dirs.sh {{ os() }}',
  # symlink our dotfiles that go directly into the home folder
  'eza -D -1 -I "_*" config/{{ os() }} | xargs stow --restow --dir config/{{ os() }} --target {{vars.home_dir}} --dotfiles {{vars.verbose_arg}}',
  # symlink the dotfiles that go into ~/.config
  'eza -D -1 -I "[a-z]*" config/{{ os() }} | xargs stow --restow --dir config/{{ os() }} --target {{vars.home_dir}}/.config --dotfiles {{vars.verbose_arg}}',
]

[tasks.clean]
description = "Deletes symlinks created by stow"
confirm = "Are you sure you want to remove dotfile symlinks"
run = [
  "rm -f ~/.gitattributes",
  "rm -f ~/.gitconfig",
  "rm -f ~/.gitignore_global",
  "rm -f ~/.gemrc",
  "rm -f ~/.tmux.conf",
  "rm -f ~/.vimrc",
  "rm -f ~/.zshrc",
  "rm -f ~/.zsh_plugins.txt",
  "rm -r ~/.config/jj",
  "rm -r ~/.config/nvim",
  "rm -r ~/.config/mise",
  "rm -r ~/.config/zellij"
]

[tasks.create_config_dirs]
description = "Ensures directories needed for creating stow symlinks exist"
run = "scripts/create_config_dirs.sh {{ os() }}"
sources = ["config/{{ os() }}/_*"]
outputs = { auto = true }

[tasks.list-configs]
hide = true
quiet = true
description = "List the stow packages"
run = 'eza -D -1 config'
