"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Chris Ortman"
email = "chris-ortman@uiowa.edu"

[ui]
diff-editor = ["kdiff3", "$left", "$right"]
merge-editor = ["kdiff3", "$left", "$base", "$right", "-o", "$output"]
#default-command = "log-recent"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
log-recent = ["log", "-r", "current() & recent()"]
wut = ["log", "-r", "work()"]
pe = ["prev","--edit"]
ne = ["next", "--edit"]
ep = ["prev","--edit"]
en = ["next", "--edit"]

[revset-aliases]
# set all remote bookmarks (commits pushed to remote branches) to be immutable
# https://zerowidth.com/2025/jj-tips-and-tricks/
'immutable_heads()' = "builtin_immutable_heads() | remote_bookmarks()"
'default()' = 'coalesce(trunk(), root())::present(@) | ancestors(visible_heads(), 2)'
'current()' = 'coalesce(trunk(),root())::present(@) | ancestors(visible_heads() & recent(), 2)'
'work()' = 'ancestors((visible_heads() & mine()) | (mine() & bookmarks()), 3)'
'recent()' = 'committer_date(after:"1 month ago")'
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'review(x)' = 'author(x) & author_date(before:1am) & (author_date(after:yesterday) | committer_date(after:yesterday))'

[template-aliases]
empty_commit_marker = 'label("empty", "(empty)")'
full = 'builtin_log_compact_full_description(self)'
'builtin_log_compact_full_description(commit)' = '''
if(commit.root(),
  format_root_commit(commit),
  label(
    separate(" ",
      if(commit.current_working_copy(), "working_copy"),
      if(commit.immutable(), "immutable", "mutable"),
      if(commit.conflict(), "conflicted"),
    ),
    concat(
      format_short_commit_header(commit) ++ "\n",
      separate(" ",
        if(commit.empty(), empty_commit_marker),
        if(commit.description(),
          commit.description().trim_end() ++ "\n",
          label(if(commit.empty(), "empty"), description_placeholder),
        ),
      ) ++ "\n",
    ),
  )
)
'''
esterday = 'commit_id.short() ++ " " ++ author.name() ++ " [A:" ++ author.timestamp().format("%Y-%m-%d") ++ " C:" ++ committer.timestamp().format("%Y-%m-%d") ++ "] " ++ if(remote_bookmarks, remote_bookmarks ++ " ", "") ++ description.first_line()'
[colors]
# Highlight hunks with background
"diff removed token" = { underline = false }
"diff added token" = {  underline = false }
# Alternatively, swap colors
"diff token" = { reverse = false, underline = false }

